FROM python:3.11-slim

WORKDIR /mlflow

RUN apt-get update && \
    apt-get install -y curl sqlite3 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install mlflow==2.9.2 psutil

EXPOSE 5050

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "/mlflow/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5050"]